### ISSUE TITLE
行事曆須更新

### ISSUE THREAD

**Issue by ncuelink** [nsysu-code-club/NSYSU-AP#76]
[school_schedule.pdf.pdf](https://github.com/nsysu-code-club/NSYSU-AP/files/14322826/school_schedule.pdf.pdf)

**Comment by abc873693** [comment]
感謝回報，雙平台是透過後台更新，桌面版已透過這邊更新
https://github.com/nsysu-code-club/NSYSU-AP/tree/4adda4822f20e0508763d56a4ebad2b68dabd644
